# Rails 5 style secrets.yml [1]

# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4766b82884f962bbce90336b9b59bf1dcd4ea2772cf1913a72b5db14ab8b341f8b343e32dde686754f76934909fc40f26278bb5dcfdc8143e8f5ec6abfcdb09a

test:
  secret_key_base: 96794511ff00227add9f14b3954aa2f26bf65aae864ce3f4ad460abb00ffa64762eb2100945a931392e268e4ea96d25d65e2af9327fc7bccdf5ab2ce6801079f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

# [1] Use of `secrets` instead of `credentials` makes for a container-ready deploy on Heroku (easier setup for open source)
#     This file is no longer added by default with Rails and has been included manually.
